In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
from datetime import datetime

In [2]:
covid_df= pd.read_csv(r'C:\Users\swapn\Downloads\covid_19_india.csv')

In [3]:
covid_df.head(10)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
5,6,2020-02-04,6:00 PM,Kerala,3,0,0,0,3
6,7,2020-02-05,6:00 PM,Kerala,3,0,0,0,3
7,8,2020-02-06,6:00 PM,Kerala,3,0,0,0,3
8,9,2020-02-07,6:00 PM,Kerala,3,0,0,0,3
9,10,2020-02-08,6:00 PM,Kerala,3,0,0,0,3

In [4]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sno                       18110 non-null  int64
 1   Date                      18110 non-null  object
 2   Time                      18110 non-null  object
 3   State/UnionTerritory      18110 non-null  object
 4   ConfirmedIndianNational   18110 non-null  object
 5   ConfirmedForeignNational  18110 non-null  object
 6   Cured                     18110 non-null  int64
 7   Deaths                    18110 non-null  int64
 8   Confirmed                 18110 non-null  int64
dtypes: int64(4), object(5)
memory usage: 1.2+ MB

In [5]:
covid_df.describe()

                Sno         Cured         Deaths     Confirmed
count  18110.000000  1.811000e+04   18110.000000  1.811000e+04
mean    9055.500000  2.786375e+05    4052.402264  3.010314e+05
std     5228.051023  6.148909e+05   10919.076411  6.561489e+05
min        1.000000  0.000000e+00       0.000000  0.000000e+00
25%     4528.250000  3.360250e+03      32.000000  4.376750e+03
50%     9055.500000  3.336400e+04     588.000000  3.977350e+04
75%    13582.750000  2.788698e+05    3643.750000  3.001498e+05
max    18110.000000  6.159676e+06  134201.000000  6.363442e+06

In [6]:
vaccine_df= pd.read_csv(r'C:\Users\swapn\Downloads\covid_vaccine_statewise.csv')

In [7]:
vaccine_df.head(10)

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
5,21/01/2021,India,365965.0,32226.0,12600.0,365965.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,132784.0,233143.0,38.0,365965.0
6,22/01/2021,India,549381.0,36988.0,14115.0,549381.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,193899.0,355402.0,80.0,549381.0
7,23/01/2021,India,759008.0,43076.0,15605.0,759008.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,267856.0,491049.0,103.0,759008.0
8,24/01/2021,India,835058.0,49851.0,18111.0,835058.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,296283.0,538647.0,128.0,835058.0
9,25/01/2021,India,1277104.0,55151.0,19682.0,1277104.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,444137.0,832766.0,201.0,1277104.0

# Drop function

In [8]:
covid_df.drop(["Sno","Time","ConfirmedIndianNational","ConfirmedForeignNational"], inplace= True, axis = 1)

In [9]:
covid_df

             Date State/UnionTerritory    Cured  Deaths  Confirmed
0      2020-01-30               Kerala        0       0          1
1      2020-01-31               Kerala        0       0          1
2      2020-02-01               Kerala        0       0          2
3      2020-02-02               Kerala        0       0          3
4      2020-02-03               Kerala        0       0          3
...           ...                  ...      ...     ...        ...
18105  2021-08-11            Telangana   638410    3831     650353
18106  2021-08-11              Tripura    77811     773      80660
18107  2021-08-11          Uttarakhand   334650    7368     342462
18108  2021-08-11        Uttar Pradesh  1685492   22775    1708812
18109  2021-08-11          West Bengal  1506532   18252    1534999

[18110 rows x 5 columns]

# Change Daate Format

In [11]:
covid_df.Date= pd.to_datetime(covid_df.Date)

In [12]:
covid_df.head(5)

        Date State/UnionTerritory  Cured  Deaths  Confirmed
0 2020-01-30               Kerala      0       0          1
1 2020-01-31               Kerala      0       0          1
2 2020-02-01               Kerala      0       0          2
3 2020-02-02               Kerala      0       0          3
4 2020-02-03               Kerala      0       0          3

In [13]:
#Active cases 
covid_df["Active_Cases"]= covid_df.Confirmed -(covid_df.Cured + covid_df.Deaths)
covid_df.tail()

,Date,State/UnionTerritory,Cured,Deaths,Confirmed,Active_Cases
18105,2021-08-11,Telangana,638410,3831,650353,8112
18106,2021-08-11,Tripura,77811,773,80660,2076
18107,2021-08-11,Uttarakhand,334650,7368,342462,444
18108,2021-08-11,Uttar Pradesh,1685492,22775,1708812,545
18109,2021-08-11,West Bengal,1506532,18252,1534999,10215

In [14]:
#pivot
Statewise=pd.pivot_table(covid_df,values=["Confirmed","Deaths","Cured"],index= "State/UnionTerritory",aggfunc= max)

In [15]:
Statewise["Recovery Rate"]= Statewise["Cured"]/Statewise["Confirmed"]*100

In [16]:
Statewise["Mortality Rate"]= Statewise["Deaths"]/Statewise["Confirmed"]*100

In [17]:
Statewise.sort_values(by="Confirmed",ascending = False)

,Confirmed,Cured,Deaths,Recovery Rate,Mortality Rate
State/UnionTerritory,,,,,
Maharashtra,6363442,6159676,134201,96.797865,2.108937
Maharashtra***,6229596,6000911,130753,96.329056,2.098900
Kerala,3586693,3396184,18004,94.688450,0.501967
Karnataka,2921049,2861499,36848,97.961349,1.261465
Karanataka,2885238,2821491,36197,97.790581,1.254559
Tamil Nadu,2579130,2524400,34367,97.877967,1.332504
Andhra Pradesh,1985182,1952736,13564,98.365591,0.683262
Uttar Pradesh,1708812,1685492,22775,98.635309,1.332797
West Bengal,1534999,1506532,18252,98.145471,1.189056
Delhi,1436852,1411280,25068,98.220276,1.744647
Chhattisgarh,1003356,988189,13544,98.488373,1.349870
Odisha,988997,972710,6565,98.353180,0.663804
Rajasthan,953851,944700,8954,99.040626,0.938721
Gujarat,825085,814802,10077,98.753704,1.221329
Madhya Pradesh,791980,781330,10514,98.655269,1.327559
Madhya Pradesh***,791656,780735,10506,98.620487,1.327092
Haryana,770114,759790,9652,98.659419,1.253321
Bihar,725279,715352,9646,98.631285,1.329971
Bihar****,715730,701234,9452,97.974655,1.320610
Telangana,650353,638410,3831,98.163613,0.589065
Punjab,599573,582791,16322,97.201008,2.722271
Assam,576149,559684,5420,97.142232,0.940729
Telengana,443360,362160,2312,81.685312,0.521472
Jharkhand,347440,342102,5130,98.463620,1.476514
Uttarakhand,342462,334650,7368,97.718871,2.151480
Jammu and Kashmir,322771,317081,4392,98.237140,1.360717
Himachal Pradesh,208616,202761,3537,97.193408,1.695460
Himanchal Pradesh,204516,200040,3507,97.811418,1.714780
Goa,172085,167978,3164,97.613389,1.838626
Puducherry,121766,119115,1800,97.822873,1.478245
Manipur,105424,96776,1664,91.796934,1.578388
Tripura,80660,77811,773,96.467890,0.958344
Meghalaya,69769,64157,1185,91.956313,1.698462
Chandigarh,61992,61150,811,98.641760,1.308233
Arunachal Pradesh,50605,47821,248,94.498567,0.490070
Mizoram,46320,33722,171,72.802245,0.369171
Nagaland,28811,26852,585,93.200514,2.030474
Sikkim,28018,25095,356,89.567421,1.270612
Ladakh,20411,20130,207,98.623291,1.014159
Dadra and Nagar Haveli and Daman and Diu,10654,10646,4,99.924911,0.037545
Dadra and Nagar Haveli,10377,10261,4,98.882143,0.038547
Lakshadweep,10263,10165,51,99.045114,0.496931
Cases being reassigned to states,9265,0,0,0.000000,0.000000
Andaman and Nicobar Islands,7548,7412,129,98.198198,1.709062
Unassigned,77,0,0,0.000000,0.000000
Daman & Diu,2,0,0,0.000000,0.000000

In [18]:
Statewise.style.background_gradient(cmap="cubehelix")

In [21]:
## Top 10 Cases state
top_10_active_cases=covid_df.groupby(by="State/UnionTerritory").max()[["Active_Cases","Date"]].sort_values(by=["Active_Cases"],ascending = False).reset_index

In [22]:
top_10_active_cases

<bound method DataFrame.reset_index of                                           Active_Cases       Date
State/UnionTerritory
Maharashtra                                     701614 2021-08-11
Karnataka                                       605515 2021-08-11
Kerala                                          445692 2021-08-11
Tamil Nadu                                      313048 2021-08-11
Uttar Pradesh                                   310783 2021-08-11
Rajasthan                                       212753 2021-08-11
Andhra Pradesh                                  211554 2021-08-11
Gujarat                                         148297 2021-08-11
West Bengal                                     132181 2021-08-11
Chhattisgarh                                    131245 2021-08-11
Haryana                                         116867 2021-08-11
Bihar                                           115152 2021-08-11
Madhya Pradesh                                  111366 2021-08-11
Odisha                                          106493 2021-08-11
Delhi                                           103424 2021-08-11
Maharashtra***                                   97932 2021-07-21
Telangana                                        80695 2021-08-11
Uttarakhand                                      80000 2021-08-11
Punjab                                           79963 2021-08-11
Telengana                                        78888 2021-05-01
Jharkhand                                        61195 2021-08-11
Assam                                            56295 2021-08-11
Jammu and Kashmir                                52848 2021-08-11
Himachal Pradesh                                 40008 2021-08-11
Goa                                              32953 2021-08-11
Karanataka                                       27550 2021-07-20
Puducherry                                       18277 2021-08-11
Mizoram                                          13101 2021-08-11
Manipur                                          10922 2021-08-11
Cases being reassigned to states                  9265 2020-07-18
Chandigarh                                        8653 2021-08-11
Tripura                                           8302 2021-08-11
Meghalaya                                         8255 2021-08-11
Nagaland                                          5049 2021-08-11
Bihar****                                         5044 2021-06-11
Arunachal Pradesh                                 4465 2021-08-11
Sikkim                                            4306 2021-08-11
Lakshadweep                                       2320 2021-08-11
Dadra and Nagar Haveli and Daman and Diu          2081 2021-08-11
Ladakh                                            2041 2021-08-11
Andaman and Nicobar Islands                       1154 2021-08-11
Himanchal Pradesh                                  969 2021-07-20
Madhya Pradesh***                                  415 2021-07-13
Dadra and Nagar Haveli                             250 2021-06-05
Unassigned                                          77 2020-04-03
Daman & Diu                                          2 2020-06-11>

In [38]:
vaccine_df

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7840,11/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7841,12/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7842,13/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7843,14/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
Male=vaccine_df["Male(Individuals Vaccinated)"].sum()
Female=vaccine_df["Female(Individuals Vaccinated)"].sum()
px.pie(names=["Male","Female"],values=["Male","Female"],title="Male and Female Vaccination")